### ISSUE TITLE
Adding attackSpeed nbt to item

### ISSUE THREAD

**Issue by gustaavik** [portlek/BukkitItemBuilder#119]
Trying to add `generic.attackSpeed` to an item using `ItemStackBuild.customData()` but getting the following error: https://pastebin.com/48iPd5nZ

![image](https://user-images.githubusercontent.com/41763143/104110787-4a222800-52db-11eb-98e6-a852d62ee613.png)

I have tried the to switch the arguments, that returns same error

**Comment by portlek** [comment]
you should use attribute modifier methods to edit attributes, not the custom data.

**Comment by gustaavik** [comment]
Also for 1.8? Because I can't find any Attribute class

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/104172941-1992d900-5416-11eb-9538-7fcc5ddc5b94.png)
because its for 14 and later

**Comment by portlek** [comment]
also, the attack speed came at 1.9
![image](https://user-images.githubusercontent.com/12835420/104173303-9b830200-5416-11eb-809b-bcfd27112317.png)
it's not for 1.8

**Comment by gustaavik** [comment]
oh, guess I should have done some researched before hand :/
